ZarrReader: HCS validation fixes
ome/ZarrReader pull request #24
Opened 2022-03-29 18:55 UTC by dgault

This includes a number of fixes for validation issues reported in https://github.com/ome/ZarrReader/issues/22
It also includes some additional fixes for multi res HCS data discovered during testing.

To test you can run the below and verify that no validation issues are reported and that the resolution levels are properly detected:
`BF_CP=/bio-formats-build/ZarrReader/target/OMEZarrReader-0.1.3-SNAPSHOT-jar-with-dependencies.jar /bio-formats-build/bioformats/tools/showinf -nopix -noflat -omexml /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs `

Fixes #22

2022-03-30 00:01 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [BIOFORMATS-push#51](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/51/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/51/consoleText) for more details.
Possible conflicts:
  - PR #23 dgault 'Fixes for dimension and tiling issues'
    - src/loci/formats/in/ZarrReader.java

--conflicts

2022-04-20 00:01 UTC, snoopycrimecop commented
Conflicting PR. Removed from build [BIOFORMATS-push#72](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/72/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-push/72/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/loci/formats/in/ZarrReader.java

--conflicts

2022-04-20 05:39 UTC, sbesson commented
It looks like `origin/main` will need to be merge into this branch now that https://github.com/ome/ZarrReader/pull/29 has been included

2022-04-20 06:47 UTC, joshmoore commented
@dgault: I've pushed a merge commit if wouldn't mind reviewing it.

2022-04-21 15:23 UTC, dgault commented
There are 4 main things to test with this PR:

**Validation fixes**: This relates to the original issue reported: https://github.com/ome/ZarrReader/issues/22
Testing using `idr/idr0094A/7751.zarr` and `showinf -nopix -omexml` should no longer report any validation warnings

**8 bit data**: Without this PR 8 bit data would display as a blank plane. With the PR included 8bit data should display correctly. Any sample file with 8bit pixel data should be suitable for testing, Petr's data at `uod/idr-scratch/test.zarr` should be suitable.

**Multi Image, Multi Resolutions**: Without this PR multi resolutions on the first image were detected correctly but for subsequent images the resolution levels were not detected. With this PR the resolution levels should be correctly detected for all images. This can be tested using `v0.4/multi-image.ome.zarr`

**Default DimensionOrder**: This was discovered using Petr's test data, in this case the dimension order is not present in the Zarr attributes and the default value was being used, however without this PR there was an inconsistency in the reader for this default order. This has now been corrected to use XYZCT. The file to test would be `uod/idr-scratch/petr-test/multifile-Z1.ome.zarr`. This file should have 5 z slices, without this PR it would display as 5 timepoints or just as a single plane (the XML would be correct and could lead to some odd behaviour in the client).

2022-04-22 15:36 UTC, pwalczysko commented
Testing 

``8 bit data`` issue (nr. 2 from https://github.com/ome/ZarrReader/pull/24#issuecomment-1105375694)
together with 
``Default Dimension Order``  issue (nr. 4 from https://github.com/ome/ZarrReader/pull/24#issuecomment-1105375694)
Test with this PR in Fiji
Pixel data look good
![Screenshot 2022-04-22 at 16 30 59](https://user-images.githubusercontent.com/2478303/164746530-77ffdfd1-d40a-4789-afe2-45ed38696840.png)

Dimension order looks good
![Screenshot 2022-04-22 at 16 27 55](https://user-images.githubusercontent.com/2478303/164746184-c0d8bbd6-a1ab-4cd5-a8e0-1bc969adab69.png)

The image is z=5 as expected.

Without this PR
Pixel data are blank on z 2-5. But the other problems detected in OMERO are not visible.

This looks good, but maybe for other tests we would profit from having merge-ci back ? Or any suggestions for usage of an OMERO server ?

2022-04-22 15:43 UTC, pwalczysko commented
Tried to test also Ad 3 **Multi-image multi resolutions** from https://github.com/ome/ZarrReader/pull/24#issuecomment-1105375694.
Without this PR I am getting locally (@dgault advised that the errors in the output below are rather connected with dimenstion order, no validation errors are visible)

<details>

```
BF_CP=/Users/pwalczysko/Downloads/OMEZarrReader-0.1.5-withoutPR-jar-with-dependencies.jar /Users/pwalczysko/Downloads/bftools/showinf -nopix -noflat -omexml  /Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/pwalczysko/Downloads/bftools/bioformats_package.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/pwalczysko/Downloads/OMEZarrReader-0.1.5-withoutPR-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Checking file format [Zarr]
Initializing reader
ZarrReader initializing /Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
Invalid dimension order: XYXYXYXYCTZ
ome.xml.model.enums.EnumerationException: 'XYXYXYXYCTZ' not a supported value of 'class ome.xml.model.enums.DimensionOrder'
	at ome.xml.model.enums.DimensionOrder.fromString(DimensionOrder.java:106)
	at loci.formats.MetadataTools.populatePixelsOnly(MetadataTools.java:299)
	at loci.formats.MetadataTools.populateMetadata(MetadataTools.java:262)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:151)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:116)
	at loci.formats.in.ZarrReader.initFile(ZarrReader.java:354)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
Exception in thread "main" java.lang.IllegalArgumentException: Invalid dimension order: XYXYXYXYCTZ
	at loci.formats.FormatTools.getZCTCoords(FormatTools.java:615)
	at loci.formats.FormatTools.getZCTCoords(FormatTools.java:565)
	at loci.formats.FormatReader.getZCTCoords(FormatReader.java:1140)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:196)
	at loci.formats.MetadataTools.populatePixels(MetadataTools.java:116)
	at loci.formats.in.ZarrReader.initFile(ZarrReader.java:354)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

</details>

With this PR I am getting no errors . Although no validation errors were seen in the test without this PR above, the absence of any errors lwith this PR ook good.

<details>

```
BF_CP=/Users/pwalczysko/Downloads/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar /Users/pwalczysko/Downloads/bftools/showinf -nopix -noflat -omexml  /Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/pwalczysko/Downloads/bftools/bioformats_package.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/pwalczysko/Downloads/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Checking file format [Zarr]
Initializing reader
ZarrReader initializing /Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
Parsing schema path
http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd
Validating OME-XML
No validation errors found.
Initialization took 0.709s

Reading core metadata
filename = /Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
Used files:
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zattrs
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/.zgroup
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s2/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s2/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/.zattrs
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/.zgroup
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s1/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s1/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s1/0/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s1/1/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s1/1/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/0/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/0/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/0/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/1/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/1/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/1/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/1/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/3/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/3/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/3/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/3/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/2/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/2/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/2/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-3/s0/2/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s2/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s2/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/.zattrs
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/.zgroup
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s1/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s1/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s1/0/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s1/1/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s1/1/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/0/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/0/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/0/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/0/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/1/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/1/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/1/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/1/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/3/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/3/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/3/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/3/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/2/0
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/2/1
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/2/3
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-2/s0/2/2
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image-0/s2/.zarray
	/Users/pwalczysko/ngff-testing/multi-image.ome.zarr/image- [...]

2022-04-22 15:48 UTC, pwalczysko commented
@sbesson happy to discuss the outputs in https://github.com/ome/ZarrReader/pull/24#issuecomment-1106638889  in more detail, - is viewing of the image necessary ?

2022-04-24 12:26 UTC, pwalczysko commented
Unfortunately, testing the [**8 bit data** paragraph](https://github.com/ome/ZarrReader/pull/24#issuecomment-1105375694)  on OMERO did not fully succeed.

Workflow: 
1. Get the prebuilt ``OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar`` with this PR from @dgault and rsync it onto ``idr0-slot3:/tmp``. 
2. ``[pwalczysko@idr0-slot3 ~]$ sudo cp /tmp/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar /uod/idr/scratch/idr2-slot3/petr-test/``
3.  Then ssh into ``idr2-slot3`` and start the docker where merge-ci is as per the https://hackmd.io/hmVE6CmATROmrAim39Uo5w
4.  ``(.venv3) bash-4.2$ cp /uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar ./uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar``
5.  then copy the OMEZarr...jar into the lib/server and lib/client as per the https://hackmd.io/hmVE6CmATROmrAim39Uo5w, this means
```
(.venv3) bash-4.2$ pwd
/home/omero/workspace/OMERO-server/OMERO.server/lib/server
(.venv3) bash-4.2$ cp /uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar 
...
(.venv3) bash-4.2$ pwd
/home/omero/workspace/OMERO-server/OMERO.server/lib/client
(.venv3) bash-4.2$ cp /uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar .
```
6. import the file in-place, all goes smoothly
7. ``omero import --transfer=ln_s --skip=checksum --parallel-upload=10  /uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/``

Also see ``import -f`` output

<details>

```
omero import -f  /uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/omero/workspace/OMERO-server/OMERO.server/lib/client/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/omero/workspace/OMERO-server/OMERO.server/lib/client/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2022-04-24 12:14:23,805 220        [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.5.11-SNAPSHOT
2022-04-24 12:14:23,822 237        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 6.10.0-SNAPSHOT revision: fe08d544114e0f95e194a6c67a0e09c952864096 date: 24 April 2022
2022-04-24 12:14:23,866 281        [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2022-04-24 12:14:24,218 633        [      main] INFO      ome.formats.importer.ImportCandidates - Depth: 4 Metadata Level: MINIMUM
2022-04-24 12:14:24,799 1214       [      main] INFO      ome.formats.importer.ImportCandidates - 6 file(s) parsed into 1 group(s) with 1 call(s) to setId in 571ms. (581ms total) [0 unknowns]
#======================================
# Group: /uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/OME/METADATA.ome.xml SPW: false Reader: loci.formats.in.ZarrReader
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/OME/METADATA.ome.xml
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/.zattrs
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/.zattrs
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/.zarray
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/0/0/3/0/0
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/0/0/2/0/0
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/0/0/4/0/0
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/0/0/1/0/0
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/0/0/0/0/0/0
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/0/.zgroup
/uod/idr-scratch/petr-test/multifile-Z1.ome.zarr/.zgroup
```

</details>

Nevertheless, **the resulting image in OMERO does not seem to have correct pixel values**, all looks black, see
user-3 https://merge-ci.openmicroscopy.org/web/webclient/?show=image-229565
The positive side is that the dimensions of the image (t=1, z=5) and the number of the images (just 1) is correct.

2022-04-24 13:05 UTC, pwalczysko commented
@dgault @sbesson edited https://github.com/ome/ZarrReader/pull/24#issuecomment-1107831121 - after server restart and reimport, all looks good.

2022-04-24 13:19 UTC, pwalczysko commented
Re: **Validation fixes** (point 1 of https://github.com/ome/ZarrReader/pull/24#issuecomment-1107831121

```
BF_CP=OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar  bftools/showinf -nopix -omexml /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/uod/idr-scratch/petr-test/bftools/bioformats_package.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Checking file format [Zarr]
Initializing reader
ZarrReader initializing /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs
Exception in thread "main" java.lang.IllegalArgumentException: Invalid index: -1
	at loci.formats.FormatReader.coreIndexToSeries(FormatReader.java:1328)
	at loci.formats.in.ZarrReader.parseWells(ZarrReader.java:686)
	at loci.formats.in.ZarrReader.parsePlate(ZarrReader.java:656)
	at loci.formats.in.ZarrReader.initFile(ZarrReader.java:362)
	at loci.formats.FormatReader.setId(FormatReader.java:1443)
	at loci.formats.ImageReader.setId(ImageReader.java:849)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
```

2022-04-24 13:23 UTC, pwalczysko commented
In summary, the tests in https://github.com/ome/ZarrReader/pull/24#issuecomment-1107831121 are as follows:

**Validation fixes** fails for me with https://github.com/ome/ZarrReader/pull/24#issuecomment-1107840675 (tested on idr2-slot3)
**8-bit..** fully passes on Fiji and OMERO
**Multi Image, Multi Resolutions** passes on the CLI using BF tools, tested locally MacOS
**Default DimensionOrder:** passes fully on Fiji and OMERO

Seems to me out of 4 tests, 2 full passes, 1 pass with question (OMERO test needed ?) and 1 fail.

2022-04-24 13:25 UTC, pwalczysko requested changes
Please comment on the fail [of the Validation fixes test ](https://github.com/ome/ZarrReader/pull/24#issuecomment-1107840675)

2022-04-26 14:12 UTC, dgault commented
It seems something has likely broken during the conflict merges or later fixes. I will try and get another commit to resolve the issue and relist for testing when ready

2022-04-28 13:30 UTC, pwalczysko commented
The error reported in https://github.com/ome/ZarrReader/pull/24#issuecomment-1107840675 is now fixed

<details>

```
BF_CP=OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar  bftools/showinf -nopix -omexml /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/uod/idr-scratch/petr-test/bftools/bioformats_package.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/uod/idr-scratch/petr-test/OMEZarrReader-0.1.5-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Checking file format [Zarr]
Initializing reader
ZarrReader initializing /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs
Parsing schema path
http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd
Validating OME-XML
No validation errors found.
Initialization took 53.179s

Reading core metadata
filename = /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/.zattrs
Used files:
......
182000 of lines of output
....
}</Value>
      </XMLAnnotation>
      <XMLAnnotation ID="Annotation:961" Namespace="openmicroscopy.org/OriginalMetadata">
         <Value>
            <OriginalMetadata>
               <Key>Axis:0:1</Key>
               <Value>x</Value>
            </OriginalMetadata>
         </Value>
      </XMLAnnotation>
      <XMLAnnotation ID="Annotation:962" Namespace="openmicroscopy.org/OriginalMetadata">
         <Value>
            <OriginalMetadata>
               <Key>Axis:0:0</Key>
               <Value>y</Value>
            </OriginalMetadata>
         </Value>
      </XMLAnnotation>
   </StructuredAnnotations>
</OME>
```

</details>

2022-04-28 13:51 UTC, pwalczysko commented
In summary, all looks good. The error is fixed, all files are having either a good ``omero import -f`` output or were imported to omero.
The only slight worry is that import to omero of 
``/uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/`` somehow expires without warning after a long wait. But ``import -f`` is looking sound.

<details>

```
omero import -f  /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/
2022-04-28 13:43:52,046 253        [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.5.11-SNAPSHOT
2022-04-28 13:43:52,073 280        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 6.10.0-SNAPSHOT revision: a3e43d1b3c1c1cbbae7d42a4265d67c1c0c3b594 date: 28 April 2022
2022-04-28 13:43:52,128 335        [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2022-04-28 13:43:52,488 695        [      main] INFO      ome.formats.importer.ImportCandidates - Depth: 4 Metadata Level: MINIMUM
2022-04-28 13:43:54,530 2737       [      main] INFO      ome.formats.importer.ImportCandidates - 1930 file(s) parsed into 0 group(s) with 0 call(s) to setId in 0ms. (2042ms total) [0 unknowns]
(.venv3) bash-4.2$ omero import -f  --depth 10 /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/
2022-04-28 13:45:16,487 214        [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.5.11-SNAPSHOT
2022-04-28 13:45:16,504 231        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 6.10.0-SNAPSHOT revision: a3e43d1b3c1c1cbbae7d42a4265d67c1c0c3b594 date: 28 April 2022
2022-04-28 13:45:16,546 273        [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2022-04-28 13:45:16,899 626        [      main] INFO      ome.formats.importer.ImportCandidates - Depth: 10 Metadata Level: MINIMUM
2022-04-28 13:45:48,264 31991      [      main] INFO      ome.formats.importer.ImportCandidates - 10570 file(s) parsed into 1 group(s) with 1 call(s) to setId in 22029ms. (31364ms total) [0 unknowns]
#======================================
# Group: /uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/G/7/7/3/0/0 SPW: false Reader: loci.formats.in.ZarrReader
/uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/G/7/7/3/0/0
/uod/idr/repos/curated/unsupported/ome-ngff/0.3/idr/idr0094A/7751.zarr/G/7/7/3/.zarray
....
```

</details>

2022-04-28 13:51 UTC, pwalczysko approved these changes

2022-04-28 14:36 UTC, merged